// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RustedMods.Data;

#nullable disable

namespace RustedMods.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227014322_AddCodeConfirmToUsers")]
    partial class AddCodeConfirmToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RustedMods.Data.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeConfirm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Socials")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RustedMods.Models.Addon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModComments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModDownload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModRequirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModScreenshots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModThumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModTrailer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addons");
                });
#pragma warning restore 612, 618
        }
    }
}
